### PR TITLE
v0.2

### PR DESCRIPTION
**Pull request by mdpiper**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update for `pymt_permamodel=0.2`.

### CODE REVIEW

**Comment by mdpiper** [comment]
@mcflugen Bump. Ethan says Tian can use this in her paper.

**Comment by mcflugen** [comment]
@mdpiper Sorry, I assumed you were a maintainer. Why don't you add yourself as a maintain of this feedstock and then I'll merge it?

**Comment by mdpiper** [comment]
See https://github.com/conda-forge/pymt_permamodel-feedstock/pull/8!

**Comment by mdpiper** [comment]
@mcflugen Thank you!

**Pull request merged**
